Select component
vocascan/vocascan-desktop pull request #30
Opened 2021-03-23 11:45 UTC by zikowang

2021-03-23 14:22 UTC, luwol03 requested changes
could you make it possible to use a translation for the display name but an extra string for the internal name?

2021-03-23 14:22 UTC, luwol03 commented on src/Components/Select/Select.jsx
> +const Select = ({ onChange = () => null, required = false, options = [], label = "", value, children, ...props }) => {
`children` is unused

2021-03-23 14:22 UTC, luwol03 commented on src/Components/Select/Select.jsx
> +            <li className="select-option" data-name={option.name} key={option.id} onClick={handleOptionClick}>
could you use for the key the second parameter of the map method?

2021-03-23 17:43 UTC, zikowang commented
@luwol03 would you please updated package-lock for me? :)

2021-03-23 18:07 UTC, zikowang commented on src/i18n/locales/en.json
> +    "noOptionMessage": "no options",
oh yes

2021-03-23 18:12 UTC, luwol03 approved these changes

2021-03-24 07:39 UTC, luwol03 commented
Can we merge this beautiful pull request? The text fields look much better after the last change.

2021-03-24 07:49 UTC, zikowang commented
> @zikowang Can we merge this beautiful pull request? The text fields look much better after the last change.

Thanks. Let's merge it.

2021-03-24 07:53 UTC, merged