about page
vocascan/vocascan-desktop pull request #68
Opened 2021-05-24 08:42 UTC by luwol03

| Status  | Type  |
| :---: | :---: |
|  :x: Hold | Feature |

## TODO

- [x] create about page
- [ ] add content

## Description

- add about page

## Motivation and Context

## Screenshots / GIFs (if appropriate):

## Checklist

- [x] I have read the **CONTRIBUTING** document.
- [x] I have considered the accessibility of my changes (i.e. did I add proper content descriptions to images, or run my changes with talkback enabled?)
- [x] I have documented my code if needed

## Resolves

2021-05-26 08:34 UTC, zikowang commented on src/Components/Details/Details.scss
> +
For better UX
```suggestion
user-select: none;
```

2021-05-26 08:36 UTC, zikowang commented on src/Components/Details/Details.scss
> +
For better UX
```suggestion
    padding-bottom: 5px;
    user-select: none;
```

2021-05-26 08:40 UTC, zikowang commented on src/screens/About/About.scss
> +
We need margin bottom here as well
```suggestion
    margin: 40px 0;
```

2021-05-26 09:10 UTC, zikowang requested changes

2021-05-26 22:08 UTC, noctera approved these changes

2021-05-27 05:41 UTC, zikowang approved these changes

2021-05-27 08:07 UTC, merged